In [1]:
import pandas as pd
import plotly.express as px
from datetime import datetime

In [2]:
metadata_path = '../../config/metadata.tsv'
bed_targets_path = '../../config/ag-vampir.bed'
wkdir = '../..'
dataset= "my_dataset_name"
panel= 'ag-vampir'
cohort_cols = 'taxon,location'
config_path = '../../config/config.yaml'

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("max_colwidth", None)

In [3]:
# Parameters
config_path = "/home/snagi/lstm_projects/ampseq-agvampir002/config/config_ms.yaml"
metadata_path = "results/config/metadata.tsv"
bed_targets_path = "config/ag-vampir.bed"
panel = "ag-vampir"
dataset = "ag-vampir-002"
cohort_cols = "location,taxon"
wkdir = "/home/snagi/lstm_projects/ampseq-agvampir002"

# Run information

In [4]:
time = datetime.today().strftime('%Y-%m-%d %H:%M:%S')

print(f"Dataset: {dataset}\nPanel: {panel}\nCohort columns: {cohort_cols}\n\nExecution time: {time}")

Dataset: ag-vampir-002
Panel: ag-vampir
Cohort columns: location,taxon

Execution time: 2025-04-23 21:50:53

#### Reference genome

In [5]:
import yaml 
with open(config_path, 'r') as file:
    config_yml = yaml.safe_load(file)

ref_dict = {k:v for k,v in config_yml.items() if 'reference' in k}

ref_df = pd.DataFrame.from_dict(ref_dict, orient='index').reset_index()
ref_df.columns = ['reference', 'value']
ref_df

,reference,value
0,reference-name,AgamP4
1,reference-fasta,resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa
2,reference-gff3,resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3
3,reference-snpeffdb,Anopheles_gambiae

#### Panel information

In [6]:
panel_metadata = pd.read_csv(bed_targets_path, sep="\t", header=None)
panel_metadata.columns = ['contig', 'start', 'end', 'amplicon', 'mutation', 'ref', 'alt']
contigs = panel_metadata.contig.unique()
panel_metadata

   contig     start       end amplicon      mutation  ref  alt
0      2L    209535    209536   Agam_1          AIM1    A    G
1      2L    927246    927247   Agam_2          AIM2    C    A
2      2L   1274352   1274353   Agam_3          AIM3    G    A
3      2L   1418209   1418210   Agam_4          AIM4    T    C
4      2L   1571928   1571929   Agam_5          AIM5    T    C
5      2L   1776347   1776348   Agam_6          AIM6    G    C
6      2L   1947573   1947574   Agam_7          AIM7    G    A
7      2L   2380981   2380982   Agam_8     Vgsc_tag1    T    C
8      2L   2381705   2381706   Agam_9     Vgsc_tag2    A    G
9      2L   2388594   2388595  Agam_10     Vgsc_tag3    G    T
10     2L   2391227   2391228  Agam_79    Vgsc_V402L    G  C,T
11     2L   2399996   2399997  Agam_11    Vgsc_D466H    G    C
12     2L   2403940   2403941  Agam_12     Vgsc_tag4    T    C
13     2L   2408422   2408423  Agam_13     Vgsc_tag5    C    T
14     2L   2408676   2408677  Agam_14     Vgsc_tag6    A    C
15     2L   2414061   2414062  Agam_15     Vgsc_tag7    A    T
16     2L   2416979   2416980  Agam_16    Vgsc_T791M    C    T
17     2L   2422650   2422651  Agam_17    Vgsc_L995S    T    C
18     2L   2422651   2422652  Agam_17    Vgsc_L995F    A    T
19     2L   2425051   2425052  Agam_18     Vgsc_tag8    G    A
20     2L   2425765   2425766  Agam_19     Vgsc_tag9    T    A
21     2L   2429616   2429617  Agam_80   Vgsc_I1527T    T    C
22     2L   2429744   2429745  Agam_20   Vgsc_N1570Y    A    T
23     2L   2429896   2429897  Agam_20   Vgsc_E1597G    A    G
24     2L   2430423   2430424  Agam_21   Vgsc_A1746S    G    T
25     2L   2430816   2430817  Agam_22   Vgsc_V1853I    G    A
26     2L   2430862   2430863  Agam_22   Vgsc_I1868T    C    T
27     2L   2430879   2430880  Agam_22   Vgsc_P1874S    C    T
28     2L   2430880   2430881  Agam_22   Vgsc_P1874L    C    T
29     2L   2431004   2431005  Agam_23          AIM8    T    C
30     2L   2431060   2431061  Agam_23   Vgsc_A1934V    C    T
31     2L   2432418   2432419  Agam_24    Vgsc_tag10    T    G
32     2L   2435580   2435581  Agam_25    Vgsc_tag11    T    A
33     2L  20288131  20288132  Agam_26   Coeae1d_tag    T    C
34     2L  25429234  25429235  Agam_27     Rdl_A296S    G    T
35     2L  25429235  25429236  Agam_27     Rdl_A296G    C    G
36     2L  25635972  25635973  Agam_28   Cyp4j5_L43F    G    A
37     2L  34073194  34073195  Agam_29     34mb_tag1    C    T
38     2L  34100757  34100758  Agam_30     34mb_tag2    A    T
39     2L  34118140  34118141  Agam_31     34mb_tag3    G    A
40     2L  34118259  34118260  Agam_31     34mb_tag4    G    A
41     2R   3492073   3492074  Agam_32    Ace1_G280S    G    A
42     2R   8368730   8368731  Agam_33          AIM9    C    A
43     2R  17854286  17854287  Agam_34         AIM10    A    C
44     2R  28492878  28492879  Agam_35   Cyp6p3_I88T    A    G
45     2R  28494246  28494247  Agam_36     Cyp6_tag1    A    C
46     2R  28497562  28497563  Agam_37     Cyp6_tag2    T    C
47     2R  28497966  28497967  Agam_38  Cyp6p4_I236M    G    C
48     2R  28498191  28498192  Agam_39     Cyp6_tag3    C    G
49     2R  28499660  28499661  Agam_40     Cyp6_tag4    G    T
50     2R  28500642  28500643  Agam_41     Cyp6_tag5    G    A
51     2R  28501398  28501399  Agam_42     Cyp6_tag6    G    A
52     2R  28502735  28502736  Agam_43     Cyp6_tag7    C    A
53     2R  28502849  28502850  Agam_43     Cyp6_tag8    C    T
54     2R  48714600  48714601  Agam_81          DSX1  NaN  NaN
55     2R  48714550  48714551  Agam_82          DSX2  NaN  NaN
56     2R  49438585  49438586  Agam_44         AIM11    T    C
57     3L     65132     65133  Agam_45         AIM12    G    T
58     3L    129050    129051  Agam_46         AIM13    C    A
59     3L    193172    193173  Agam_47         AIM14    A    G
60     3L    367247    367248  Agam_48         AIM15    C    A
61     3L    380973    380974  Agam_49         AIM16    C    A
62     3L    413507    413508  Agam_50         AIM17    G    A
63     3L  11208464  11208465  Agam_51         Tep1A    A    G
64     3L  11213954  11213955  Agam_52         Tep1B    G    T
65     3R     34263     34264  Agam_53         AIM18    G    A
66     3R     35120     35121  Agam_54         AIM19    G    A
67     3R     38160     38161  Agam_55         AIM20    G    A
68     3R     42847     42848  Agam_56         AIM21    C    A
69     3R     50589     50590  Agam_57         AIM22    G    T
70     3R     71972     71973  Agam_58         AIM23    A    C
71     3R     97616     97617  Agam_59         AIM24    A    G
72     3R   8564155   8564156  Agam_60          D7R2    G    A
73     3R  28592157  28592158  Agam_61     Gste_tag1    G    A
74     3R  28595448  28595449  Agam_62     Gste_tag2    C    T
75     3R  28598056  28598057  Agam_63    Gste_F120L    G    C
76     3R  28598061  28598062  Agam_63    Gste_L119V    G    C
77     3R  28598165  28598166  Agam_63    Gste_I114T    A    G
78     3R  28600700  28600701  Agam_64     Gste_tag3    A    G
79      X  15249653  15249654  Agam_65   Cyp9k1_tag1    A    G
80      X  15251489  15251490  Agam_66   Cyp9k1_tag2    C    T
81      X  15255320  15255321  Agam_67   Cyp9k1_tag3    A    T
82      X  18758299  18758300  Agam_68         AIM25    T    C
83      X  19631624  19631625  Agam_69         AIM26    G    C
84      X  20014695  20014696  Agam_70         AIM27    C    A
85      X  20128327  20128328  Agam_71         AIM28    T    C
86      X  20129287  20129288  Agam_72         AIM29    T    G
87      X  21721800  21721801  Agam_73         AIM30    G    C
88      X  22164042  22164043  Agam_74         AIM31    T    C
89      X  22798647  22798648  Agam_75         AIM32    C    A
90      X  23468267  23468268  Agam_76         AIM33    T    A
91      X  24229845  24229846  Agam_77         AIM34    G    A
92      X  24266727  24266728  Agam_78         AIM35    T    A

#### Input metadata

In [7]:
# load panel metadata
if metadata_path.endswith('.xlsx'):
    metadata = pd.read_excel(metadata_path, engine='openpyxl')
elif metadata_path.endswith('.tsv'):
    metadata = pd.read_csv(metadata_path, sep="\t")
elif metadata_path.endswith('.csv'):
    metadata = pd.read_csv(metadata_path, sep=",")
else:
    raise ValueError("Metadata file must be .xlsx or .csv")

metadata

,sample_id,sample_name,index,index2,plate,taxon,location,country,latitude,longitude,well_letter,well_number
0,GH_01,GH_01,ATCACGTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,1
1,GH_02,GH_02,CGATGTTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,2
2,GH_03,GH_03,TTAGGCAT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,3
3,GH_04,GH_04,TGACCACT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,4
4,GH_05,GH_05,ACAGTGGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,5
5,GH_06,GH_06,GCCAATGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,6
6,GH_07,GH_07,CAGATCTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,7
7,GH_08,GH_08,ACTTGATG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,8
8,GH_09,GH_09,GATCAGCG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,9
9,GH_10,GH_10,TAGCTTGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,10
10,GH_11,GH_11,GGCTACAG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,11
11,GH_12,GH_12,CTTGTACT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,A,12
12,GH_13,GH_13,TGGTTGTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,1
13,GH_14,GH_14,TCTCGGTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,2
14,GH_15,GH_15,TAAGCGTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,3
15,GH_16,GH_16,TCCGTCTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,4
16,GH_17,GH_17,TGTACCTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,5
17,GH_18,GH_18,TTCTGTGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,6
18,GH_19,GH_19,TCTGCTGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,7
19,GH_20,GH_20,TTGGAGGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,8
20,GH_21,GH_21,TCGAGCGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,9
21,GH_22,GH_22,TGATACGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,10
22,GH_23,GH_23,TGCATAGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,11
23,GH_24,GH_24,TTGACTCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,B,12
24,GH_25,GH_25,TGCGATCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,1
25,GH_26,GH_26,TTCCTGCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,2
26,GH_27,GH_27,TAGTGACT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,3
27,GH_28,GH_28,TACAGGAT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,4
28,GH_29,GH_29,TCCTCAAT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,5
29,GH_30,GH_30,TGTGGTTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,6
30,GH_31,GH_31,TAGTCTTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,7
31,GH_32,GH_32,TTCCATTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,8
32,GH_33,GH_33,TCGAAGTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,9
33,GH_34,GH_34,TAACGCTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,10
34,GH_35,GH_35,TTGGTATG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,11
35,GH_36,GH_36,TGAACTGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,C,12
36,GH_37,GH_37,TACTTCGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,1
37,GH_38,GH_38,TCTCACGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,2
38,GH_39,GH_39,TCAGGAGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,3
39,GH_40_low_vol,GH_40_low_vol,TAAGTTCG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,4
40,GH_41,GH_41,TCCAGTCG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,5
41,GH_42,GH_42,TGTATGCG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,6
42,GH_43,GH_43,TCATTGAG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,7
43,GH_44,GH_44,TGGCTCAG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,8
44,GH_45,GH_45,TATGCCAG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,9
45,GH_46,GH_46,TCAGATTC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,10
46,GH_47,GH_47,TACTAGTC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,11
47,GH_48,GH_48,TTCAGCTC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,D,12
48,GH_49,GH_49,TGTCTATC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,1
49,GH_50,GH_50,TATGTGGC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,2
50,GH_51,GH_51,TTACTCGC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,3
51,GH_52,GH_52,TCGTTAGC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,4
52,GH_53,GH_53,TACCGAGC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,5
53,GH_54,GH_54,TGTTCTCC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,6
54,GH_55,GH_55,TTCGCACC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,7
55,GH_56,GH_56,TTGCGTAC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,8
56,GH_57,GH_57,TCTACGAC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,9
57,GH_58,GH_58,TGACAGAC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,10
58,GH_59,GH_59,TAGAACAC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,11
59,GH_60,GH_60,TCATCCTA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,E,12
60,GH_61,GH_61,TGCTGATA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,1
61,GH_62,GH_62,TAGACGGA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,2
62,GH_63,GH_63,TGTGAAGA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,3
63,GH_64,GH_64,TCTCTTCA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,4
64,GH_65_low_vol,GH_65_low_vol,TTGTTCCA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,5
65,GH_66,GH_66,TGAAGCCA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,6
66,GH_67,GH_67,TACCACCA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,7
67,GH_68,GH_68,TGCGTGAA,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,8
68,GH_69,GH_69,GGTGAGTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,9
69,GH_70,GH_70,GATCTCTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,10
70,GH_71,GH_71,GTGTCCTT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,11
71,GH_72,GH_72,GACGGATT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,F,12
72,GH_73,GH_73,GCAACATT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,1
73,GH_74,GH_74,GGTCGTGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,2
74,GH_75,GH_75,GAATCTGT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,3
75,GH_76,GH_76,GTACATCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,4
76,GH_77,GH_77,GAGGTGCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,5
77,GH_78,GH_78,GCATGGCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,6
78,GH_79,GH_79,GTTAGCCT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,7
79,GH_80_low_vol,GH_80_low_vol,GTCGCTAT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,8
80,GH_81,GH_81,GGAATGAT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,9
81,GH_82,GH_82,GAGCCAAT,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,10
82,GH_83,GH_83,GCTCCTTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,11
83,GH_84,GH_84,GTAAGGTG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,G,12
84,GH_85,GH_85,GAGGATGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,1
85,GH_86,GH_86,GTTGTCGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,2
86,GH_87,GH_87,GGATTAGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,3
87,GH_88,GH_88,GATAGAGG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,4
88,GH_89,GH_89,GTGTGTCG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,5
89,GH_90,GH_90,GCAATCCG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,6
90,GH_91,GH_91,GACCTTAG,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,7
91,GH_92,GH_92,GCCTGTTC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,8
92,GH_93,GH_93,GCACTGTC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,9
93,GH_94,GH_94,GCTAACTC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,10
94,GH_95,GH_95,GATTCATC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,11
95,GH_Negative,GH_Negative,GTCTTGGC,CCTATCCT,3,NaN,Obuasi,Ghana,NaN,NaN,H,12
96,GM_01,GM_01,ATCACGTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,1
97,GM_02,GM_02,CGATGTTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,2
98,GM_03,GM_03,TTAGGCAT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,3
99,GM_04,GM_04,TGACCACT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,4
100,GM_05,GM_05,ACAGTGGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,5
101,GM_06,GM_06,GCCAATGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,6
102,GM_07,GM_07,CAGATCTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,7
103,GM_08,GM_08,ACTTGATG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,8
104,GM_09,GM_09,GATCAGCG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,9
105,GM_10,GM_10,TAGCTTGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,10
106,GM_11,GM_11,GGCTACAG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,11
107,GM_12,GM_12,CTTGTACT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,A,12
108,GM_13,GM_13,TGGTTGTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,1
109,GM_14,GM_14,TCTCGGTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,2
110,GM_15,GM_15,TAAGCGTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,3
111,GM_16,GM_16,TCCGTCTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,4
112,GM_17,GM_17,TGTACCTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,5
113,GM_18,GM_18,TTCTGTGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,6
114,GM_19,GM_19,TCTGCTGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,7
115,GM_20,GM_20,TTGGAGGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,8
116,GM_21,GM_21,TCGAGCGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,9
117,GM_22,GM_22,TGATACGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,10
118,GM_23,GM_23,TGCATAGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,11
119,GM_24,GM_24,TTGACTCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,B,12
120,GM_25,GM_25,TGCGATCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,1
121,GM_26,GM_26,TTCCTGCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,2
122,GM_27,GM_27,TAGTGACT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,3
123,GM_28,GM_28,TACAGGAT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,4
124,GM_29,GM_29,TCCTCAAT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,5
125,GM_30,GM_30,TGTGGTTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,6
126,GM_31,GM_31,TAGTCTTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,7
127,GM_32,GM_32,TTCCATTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,8
128,GM_33,GM_33,TCGAAGTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,9
129,GM_34,GM_34,TAACGCTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,10
130,GM_35,GM_35,TTGGTATG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,11
131,GM_36,GM_36,TGAACTGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,C,12
132,GM_37,GM_37,TACTTCGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,1
133,GM_38,GM_38,TCTCACGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,2
134,GM_39,GM_39,TCAGGAGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,3
135,GM_40,GM_40,TAAGTTCG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,4
136,GM_41,GM_41,TCCAGTCG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,5
137,GM_42,GM_42,TGTATGCG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,6
138,GM_43,GM_43,TCATTGAG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,7
139,GM_44,GM_44,TGGCTCAG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,8
140,GM_45,GM_45,TATGCCAG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,9
141,GM_46,GM_46,TCAGATTC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,10
142,GM_47,GM_47,TACTAGTC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,11
143,GM_48,GM_48,TTCAGCTC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,D,12
144,GM_49,GM_49,TGTCTATC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,1
145,GM_50,GM_50,TATGTGGC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,2
146,GM_51,GM_51,TTACTCGC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,3
147,GM_52,GM_52,TCGTTAGC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,4
148,GM_53,GM_53,TACCGAGC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,5
149,GM_54,GM_54,TGTTCTCC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,6
150,GM_55,GM_55,TTCGCACC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,7
151,GM_56,GM_56,TTGCGTAC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,8
152,GM_57,GM_57,TCTACGAC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,9
153,GM_58,GM_58,TGACAGAC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,10
154,GM_59,GM_59,TAGAACAC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,11
155,GM_60,GM_60,TCATCCTA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,E,12
156,GM_61,GM_61,TGCTGATA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,1
157,GM_62,GM_62,TAGACGGA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,2
158,GM_63,GM_63,TGTGAAGA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,3
159,GM_64,GM_64,TCTCTTCA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,4
160,GM_65,GM_65,TTGTTCCA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,5
161,GM_66,GM_66,TGAAGCCA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,6
162,GM_67,GM_67,TACCACCA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,7
163,GM_68,GM_68,TGCGTGAA,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,8
164,GM_69,GM_69,GGTGAGTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,9
165,GM_70,GM_70,GATCTCTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,10
166,GM_71,GM_71,GTGTCCTT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,11
167,GM_72,GM_72,GACGGATT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,F,12
168,GM_73,GM_73,GCAACATT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,1
169,GM_74,GM_74,GGTCGTGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,2
170,GM_75,GM_75,GAATCTGT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,3
171,GM_76,GM_76,GTACATCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,4
172,GM_77,GM_77,GAGGTGCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,5
173,GM_78,GM_78,GCATGGCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,6
174,GM_79,GM_79,GTTAGCCT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,7
175,GM_80,GM_80,GTCGCTAT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,8
176,GM_81,GM_81,GGAATGAT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,9
177,GM_82,GM_82,GAGCCAAT,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,10
178,GM_83,GM_83,GCTCCTTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,11
179,GM_84,GM_84,GTAAGGTG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,G,12
180,GM_85,GM_85,GAGGATGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,1
181,GM_86,GM_86,GTTGTCGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,2
182,GM_87,GM_87,GGATTAGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,3
183,GM_88,GM_88,GATAGAGG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,4
184,GM_89,GM_89,GTGTGTCG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,5
185,GM_90,GM_90,GCAATCCG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,6
186,GM_91,GM_91,GACCTTAG,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,7
187,GM_92,GM_92,GCCTGTTC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,8
188,GM_93,GM_93,GCACTGTC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,9
189,GM_94,GM_94,GCTAACTC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,10
190,GM_95,GM_95,GATTCATC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,11
191,GM_96,GM_96,GTCTTGGC,GTACTGAC,8,NaN,Gambia_URR,Gambia,NaN,NaN,H,12
192,VK7_dead_01,VK7_dead_01,ATCACGTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,1
193,VK7_dead_02,VK7_dead_02,CGATGTTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,2
194,VK7_dead_03,VK7_dead_03,TTAGGCAT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,3
195,VK7_dead_04,VK7_dead_04,TGACCACT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,4
196,VK7_dead_05,VK7_dead_05,ACAGTGGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,5
197,VK7_dead_06,VK7_dead_06,GCCAATGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,6
198,VK7_alive_01,VK7_alive_01,CAGATCTG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,7
199,VK7_alive_02,VK7_alive_02,ACTTGATG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,8
200,VK7_alive_03,VK7_alive_03,GATCAGCG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,9
201,VK7_alive_04,VK7_alive_04,TAGCTTGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,10
202,VK7_alive_05,VK7_alive_05,GGCTACAG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,11
203,VK7_alive_06,VK7_alive_06,CTTGTACT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,A,12
204,VK7_dead_07,VK7_dead_07,TGGTTGTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,1
205,VK7_dead_08,VK7_dead_08,TCTCGGTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,2
206,VK7_dead_09,VK7_dead_09,TAAGCGTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,3
207,VK7_dead_10,VK7_dead_10,TCCGTCTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,4
208,VK7_dead_11,VK7_dead_11,TGTACCTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,5
209,VK7_dead_12,VK7_dead_12,TTCTGTGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,6
210,VK7_alive_07,VK7_alive_07,TCTGCTGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,7
211,VK7_alive_08,VK7_alive_08,TTGGAGGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,8
212,VK7_alive_09,VK7_alive_09,TCGAGCGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,9
213,VK7_alive_10,VK7_alive_10,TGATACGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,10
214,VK7_alive_11,VK7_alive_11,TGCATAGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,11
215,VK7_alive_12,VK7_alive_12,TTGACTCT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,B,12
216,VK7_dead_13,VK7_dead_13,TGCGATCT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,1
217,VK7_dead_14,VK7_dead_14,TTCCTGCT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,2
218,VK7_dead_15,VK7_dead_15,TAGTGACT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,3
219,VK7_dead_16,VK7_dead_16,TACAGGAT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,4
220,VK7_dead_17,VK7_dead_17,TCCTCAAT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,5
221,VK7_dead_04_dil,VK7_dead_04_dil,TGTGGTTG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,6
222,VK7_alive_13,VK7_alive_13,TAGTCTTG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,7
223,VK7_alive_14,VK7_alive_14,TTCCATTG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,8
224,VK7_alive_15,VK7_alive_15,TCGAAGTG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,9
225,VK7_alive_16,VK7_alive_16,TAACGCTG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,10
226,VK7_alive_17,VK7_alive_17,TTGGTATG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,11
227,VK7_alive_18,VK7_alive_18,TGAACTGG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,C,12
228,VK7_dead_18,VK7_dead_18,TACTTCGG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,1
229,VK7_dead_19,VK7_dead_19,TCTCACGG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,2
230,VK7_dead_20,VK7_dead_20,TCAGGAGG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,3
231,VK7_dead_21,VK7_dead_21,TAAGTTCG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,4
232,VK7_dead_22,VK7_dead_22,TCCAGTCG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,5
233,VK7_dead_10_dil,VK7_dead_10_dil,TGTATGCG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,6
234,VK7_alive_19,VK7_alive_19,TCATTGAG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,7
235,VK7_alive_20,VK7_alive_20,TGGCTCAG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,8
236,VK7_alive_21,VK7_alive_21,TATGCCAG,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,9
237,VK7_alive_22,VK7_alive_22,TCAGATTC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,10
238,VK7_alive_23,VK7_alive_23,TACTAGTC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,11
239,VK7_alive_24,VK7_alive_24,TTCAGCTC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,D,12
240,VK7_dead_23,VK7_dead_23,TGTCTATC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,1
241,VK7_dead_24,VK7_dead_24,TATGTGGC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,2
242,VK7_dead_25,VK7_dead_25,TTACTCGC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,3
243,VK7_dead_26,VK7_dead_26,TCGTTAGC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,4
244,VK7_dead_27,VK7_dead_27,TACCGAGC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,5
245,VK7_dead_16_dil,VK7_dead_16_dil,TGTTCTCC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,6
246,VK7_alive_25,VK7_alive_25,TTCGCACC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,7
247,VK7_alive_26,VK7_alive_26,TTGCGTAC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,8
248,VK7_alive_27,VK7_alive_27,TCTACGAC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,9
249,VK7_alive_28,VK7_alive_28,TGACAGAC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,10
250,VK7_alive_29,VK7_alive_29,TAGAACAC,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,11
251,VK7_alive_30,VK7_alive_30,TCATCCTA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,E,12
252,VK7_dead_28,VK7_dead_28,TGCTGATA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,1
253,VK7_dead_29,VK7_dead_29,TAGACGGA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,2
254,VK7_dead_30,VK7_dead_30,TGTGAAGA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,3
255,VK7_dead_31,VK7_dead_31,TCTCTTCA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,4
256,VK7_dead_32,VK7_dead_32,TTGTTCCA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,5
257,VK7_dead_22_dil,VK7_dead_22_dil,TGAAGCCA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,6
258,VK7_alive_31,VK7_alive_31,TACCACCA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,7
259,VK7_alive_32,VK7_alive_32,TGCGTGAA,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,8
260,VK7_alive_33,VK7_alive_33,GGTGAGTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,9
261,VK7_alive_34,VK7_alive_34,GATCTCTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,10
262,VK7_alive_35,VK7_alive_35,GTGTCCTT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,11
263,VK7_alive_36,VK7_alive_36,GACGGATT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,F,12
264,VK7_dead_33,VK7_dead_33,GCAACATT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,G,1
265,VK7_dead_34,VK7_dead_34,GGTCGTGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,G,2
266,VK7_dead_35,VK7_dead_35,GAATCTGT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,G,3
267,VK7_dead_36,VK7_dead_36,GTACATCT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,G,4
268,VK7_dead_37,VK7_dead_37,GAGGTGCT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,G,5
269,VK7_dead_28_dil,VK7_dead_28_dil,GCATGGCT,TATCCTCT,10,coluzzii,VK7,Burkina Faso,NaN,NaN,G,6